# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 785af29dc993c4c95029395ce0e78653b3130d412b984e03453ecec4510d940054b5b47f7335a53fdd897e23453297d1749a9d78d3992218bcbddf766708e294

test:
  secret_key_base: 76ed9dc5c986fc78ee93f9830c0f35d460e32da44b40678159c019a583ed7bf1a3617b257bdcf584d7984ab5da0a38e05ae650ff434855b639a18cf93d2bc73d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
